BSP/meta/poky/bitbake/lib/toaster/bldviewer/urls.py
#
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-
#
# BitBake Toaster Implementation
#
# Copyright (C) 2013        Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

urlpatterns = patterns('bldviewer.views',
        url(r'^builds/$', 'build', name='simple-all-builds'),
        url(r'^build/(?P<build_id>\d+)/task/$', 'task', name='simple-task'),
        url(r'^build/(?P<build_id>\d+)/packages/$', 'bpackage', name='simple-bpackage'),
        url(r'^build/(?P<build_id>\d+)/package/(?P<package_id>\d+)/files/$', 'bfile', name='simple-bfile'),
        url(r'^build/(?P<build_id>\d+)/target/(?P<target_id>\d+)/packages/$', 'tpackage', name='simple-tpackage'),
        url(r'^build/(?P<build_id>\d+)/configuration/$', 'configuration', name='simple-configuration'),
        url(r'^layers/$', 'layer', name='simple-all-layers'),
        url(r'^layerversions/(?P<layerversion_id>\d+)/recipes/.*$', 'layer_versions_recipes', name='simple-layer_versions_recipes'),
        url(r'^$', RedirectView.as_view( url= 'builds/')),
)

BSP/meta/poky/bitbake/lib/toaster/toastermain/urls.py
#
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-
#
# BitBake Toaster Implementation
#
# Copyright (C) 2013        Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.views.decorators.cache import never_cache


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # the api-s are not auto-discoverable
    url(r'^api/1.0/', include('bldviewer.api')),

    # Examples:
    # url(r'^toaster/', include('toaster.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),


    # if no application is selected, we have the magic toastergui app here
    url(r'^$', never_cache(RedirectView.as_view(url='/toastergui/'))),
)

import toastermain.settings
if toastermain.settings.MANAGED:
    urlpatterns = urlpatterns + [
        # Uncomment the next line to enable the admin:
        url(r'^admin/', include(admin.site.urls)),
    ]
# Automatically discover urls.py in various apps, beside our own
# and map module directories to the patterns

import os
currentdir = os.path.dirname(__file__)
for t in os.walk(os.path.dirname(currentdir)):
    if "urls.py" in t[2] and t[0] != currentdir:
        modulename = os.path.basename(t[0])
        urlpatterns.append( url(r'^' + modulename + '/', include ( modulename + '.urls')))

BSP/meta/poky/bitbake/lib/toaster/orm/models.py
#
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-
#
# BitBake Toaster Implementation
#
# Copyright (C) 2013        Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from django.db import models
from django.db.models import F
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

class ToasterSetting(models.Model):
    name = models.CharField(max_length=63)
    helptext = models.TextField()
    value = models.CharField(max_length=255)

class ToasterSettingDefaultLayer(models.Model):
    layer_version = models.ForeignKey('Layer_Version')

class ProjectManager(models.Manager):
    def create_project(self, name, release):
        prj = self.model(name = name, bitbake_version = release.bitbake_version, release = release)
        prj.save()

        for defaultconf in ToasterSetting.objects.filter(name__startswith="DEFCONF_"):
            name = defaultconf.name[8:]
            ProjectVariable.objects.create( project = prj,
                name = name,
                value = defaultconf.value)

        for layer in map(lambda x: x.layer, ReleaseDefaultLayer.objects.filter(release = release)):
            for branches in Branch.objects.filter(name = release.branch):
                for lv in Layer_Version.objects.filter(layer = layer, up_branch = branches ):
                    ProjectLayer.objects.create( project = prj,
                        layercommit = lv,
                        optional = False )

        return prj

    def create(self, *args, **kwargs):
        raise Exception("Invalid call to Project.objects.create. Use Project.objects.create_project() to create a project")

    def get_or_create(self, *args, **kwargs):
        raise Exception("Invalid call to Project.objects.get_or_create. Use Project.objects.create_project() to create a project")

class Project(models.Model):
    name = models.CharField(max_length=100)
    short_description = models.CharField(max_length=50, blank=True)
    bitbake_version = models.ForeignKey('BitbakeVersion')
    release     = models.ForeignKey("Release")
    created     = models.DateTimeField(auto_now_add = True)
    updated     = models.DateTimeField(auto_now = True)
    # This is a horrible hack; since Toaster has no "User" model available when
    # running in interactive mode, we can't reference the field here directly
    # Instead, we keep a possible null reference to the User id, as not to force
    # hard links to possibly missing models
    user_id     = models.IntegerField(null = True)
    objects     = ProjectManager()


    def schedule_build(self):
        from bldcontrol.models import BuildRequest, BRTarget, BRLayer, BRVariable, BRBitbake
        br = BuildRequest.objects.create(project = self)

        BRBitbake.objects.create(req = br,
            giturl = self.bitbake_version.giturl,
            commit = self.bitbake_version.branch,
            dirpath = self.bitbake_version.dirpath)

        for l in self.projectlayer_set.all():
            BRLayer.objects.create(req = br, name = l.layercommit.layer.name, giturl = l.layercommit.layer.vcs_url, commit = l.layercommit.commit, dirpath = l.layercommit.dirpath)
        for t in self.projecttarget_set.all():
            BRTarget.objects.create(req = br, target = t.target, task = t.task)
        for v in self.projectvariable_set.all():
            BRVariable.objects.create(req = br, name = v.name, value = v.value)

        br.state = BuildRequest.REQ_QUEUED
        br.save()
        return br

class Build(models.Model):
    SUCCEEDED = 0
    FAILED = 1
    IN_PROGRESS = 2

    BUILD_OUTCOME = (
        (SUCCEEDED, 'Succeeded'),
        (FAILED, 'Failed'),
        (IN_PROGRESS, 'In Progress'),
    )

    search_allowed_fields = ['machine', 'cooker_log_path', "target__target", "target__target_image_file__file_name"]

    project = models.ForeignKey(Project, null = True)
    machine = models.CharField(max_length=100)
    distro = models.CharField(max_length=100)
    distro_version = models.CharField(max_length=100)
    started_on = models.DateTimeField()
    completed_on = models.DateTimeField()
    timespent = models.IntegerField(default=0)
    outcome = models.IntegerField(choices=BUILD_OUTCOME, default=IN_PROGRESS)
    errors_no = models.IntegerField(default=0)
    warnings_no = models.IntegerField(default=0)
    cooker_log_path = models.CharField(max_length=500)
    build_name = models.CharField(max_length=100)
    bitbake_version = models.CharField(max_length=50)

    def completeper(self):
        tf = Task.objects.filter(build = self)
        tfc = tf.count()
        if tfc > 0:
            completeper = tf.exclude(order__isnull=True).count()*100/tf.count()
        else:
            completeper = 0
        return completeper

    def eta(self):
        from django.utils import timezone
        eta = 0
        completeper = self.completeper()
        if self.completeper() > 0:
            eta = timezone.now() + ((timezone.now() - self.started_on)*(100-completeper)/completeper)
        return eta


    def get_sorted_target_list(self):
        tgts = Target.objects.filter(build_id = self.id).order_by( 'target' );
        return( tgts );

class ProjectTarget(models.Model):
    project = models.ForeignKey(Project)
    target = models.CharField(max_length=100)
    task = models.CharField(max_length=100, null=True)

@python_2_unicode_compatible
class Target(models.Model):
    search_allowed_fields = ['target', 'file_name']
    build = models.ForeignKey(Build)
    target = models.CharField(max_length=100)
    is_image = models.BooleanField(default = False)
    image_size = models.IntegerField(default=0)
    license_manifest_path = models.CharField(max_length=500, null=True)

    def package_count(self):
        return Target_Installed_Package.objects.filter(target_id__exact=self.id).count()

    def __str__(self):
        return self.target

class Target_Image_File(models.Model):
    target = models.ForeignKey(Target)
    file_name = models.FilePathField(max_length=254)
    file_size = models.IntegerField()

class Target_File(models.Model):
    ITYPE_REGULAR = 1
    ITYPE_DIRECTORY = 2
    ITYPE_SYMLINK = 3
    ITYPE_SOCKET = 4
    ITYPE_FIFO = 5
    ITYPE_CHARACTER = 6
    ITYPE_BLOCK = 7
    ITYPES = ( (ITYPE_REGULAR ,'regular'),
        ( ITYPE_DIRECTORY ,'directory'),
        ( ITYPE_SYMLINK ,'symlink'),
        ( ITYPE_SOCKET ,'socket'),
        ( ITYPE_FIFO ,'fifo'),
        ( ITYPE_CHARACTER ,'character'),
        ( ITYPE_BLOCK ,'block'),
        )

    target = models.ForeignKey(Target)
    path = models.FilePathField()
    size = models.IntegerField()
    inodetype = models.IntegerField(choices = ITYPES)
    permission = models.CharField(max_length=16)
    owner = models.CharField(max_length=128)
    group = models.CharField(max_length=128)
    directory = models.ForeignKey('Target_File', related_name="directory_set", null=True)
    sym_target = models.ForeignKey('Target_File', related_name="symlink_set", null=True)


class TaskManager(models.Manager):
    def related_setscene(self, task_object):
        return Task.objects.filter(task_executed=True, build = task_object.build, recipe = task_object.recipe, task_name=task_object.task_name+"_setscene")

class Task(models.Model):

    SSTATE_NA = 0
    SSTATE_MISS = 1
    SSTATE_FAILED = 2
    SSTATE_RESTORED = 3

    SSTATE_RESULT = (
        (SSTATE_NA, 'Not Applicable'), # For rest of tasks, but they still need checking.
        (SSTATE_MISS, 'File not in cache'), # the sstate object was not found
        (SSTATE_FAILED, 'Failed'), # there was a pkg, but the script failed
        (SSTATE_RESTORED, 'Succeeded'), # successfully restored
    )

    CODING_NA = 0
    CODING_PYTHON = 2
    CODING_SHELL = 3

    TASK_CODING = (
        (CODING_NA, 'N/A'),
        (CODING_PYTHON, 'Python'),
        (CODING_SHELL, 'Shell'),
    )

    OUTCOME_NA = -1
    OUTCOME_SUCCESS = 0
    OUTCOME_COVERED = 1
    OUTCOME_CACHED = 2
    OUTCOME_PREBUILT = 3
    OUTCOME_FAILED = 4
    OUTCOME_EMPTY = 5

    TASK_OUTCOME = (
        (OUTCOME_NA, 'Not Available'),
        (OUTCOME_SUCCESS, 'Succeeded'),
        (OUTCOME_COVERED, 'Covered'),
        (OUTCOME_CACHED, 'Cached'),
        (OUTCOME_PREBUILT, 'Prebuilt'),
        (OUTCOME_FAILED, 'Failed'),
        (OUTCOME_EMPTY, 'Empty'),
    )

    TASK_OUTCOME_HELP = (
        (OUTCOME_SUCCESS, 'This task successfully completed'),
        (OUTCOME_COVERED, 'This task did not run because its output is provided by another task'),
        (OUTCOME_CACHED, 'This task restored output from the sstate-cache directory or mirrors'),
        (OUTCOME_PREBUILT, 'This task did not run because its outcome was reused from a previous build'),
        (OUTCOME_FAILED, 'This task did not complete'),
        (OUTCOME_EMPTY, 'This task has no executable content'),
        (OUTCOME_NA, ''),
    )

    search_allowed_fields = [ "recipe__name", "recipe__version", "task_name", "logfile" ]

    objects = TaskManager()

    def get_related_setscene(self):
        return Task.objects.related_setscene(self)

    def get_outcome_text(self):
        return Task.TASK_OUTCOME[self.outcome + 1][1]

    def get_outcome_help(self):
        return Task.TASK_OUTCOME_HELP[self.outcome][1]

    def get_sstate_text(self):
        if self.sstate_result==Task.SSTATE_NA:

BSP/meta/poky/bitbake/lib/toaster/bldviewer/templates/simple_base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Toaster Simple Explorer</title>
<script src="{% static 'js/jquery-2.0.3.js' %}">
</script>
<script src="{% static 'js/bootstrap.js' %}">
</script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
	</head>

<body style="height: 100%">
<div style="width:100%; height: 100%; position:absolute">
<div style="width: 100%; height: 3em" class="nav">
    <ul class="nav nav-tabs">
        <li><a href="{% url "simple-all-builds" %}">All Builds</a></li>
        <li><a href="{% url "simple-all-layers" %}">All Layers</a></li>
    </ul>
</div>

<div style="overflow-y:scroll; width: 100%; position: absolute; top: 3em; bottom:70px ">
{% block pagecontent %}
{% endblock %}
</div>
<div class="navbar" style="position: absolute; bottom: 0; width:100%"><br/>About Toaster | Yocto Project </div>
</div>
</body>
</html>

BSP/meta/poky/bitbake/lib/toaster/bldviewer/templates/simple_basebuildpage.html
{% extends "simple_basetable.html" %}

{% block pagename %}
<ul class="nav nav-tabs" style="display: inline-block">
  <li><a>Build {{build.target_set.all|join:"&nbsp;"}} at {{build.started_on}} : </a></li>
  <li><a href="{% url "simple-task" build.id %}"> Tasks </a></li>
  <li><a href="{% url "simple-bpackage" build.id %}"> Build Packages </a></li>
    {% for t in build.target_set.all %}
        {% if t.is_image %}
  <li><a href="{% url "simple-tpackage" build.id t.pk %}"> Packages for {{t.target}} </a> </li>
        {% endif %}
    {% endfor %}
  <li><a href="{% url "simple-configuration" build.id %}"> Configuration </a> </li>
</ul>
     <h1>Toaster - Build {% block pagetitle %} {% endblock %}</h1>
{% endblock %}

BSP/meta/poky/bitbake/lib/toaster/bldviewer/templates/simple_basetable.html
{% extends "simple_base.html" %}

{% block pagecontent %}
<script>
function showhideTableColumn(i, sh) {
    if (sh)
        $('td:nth-child('+i+'),th:nth-child('+i+')').show();
    else
        $('td:nth-child('+i+'),th:nth-child('+i+')').hide();
}


function filterTableRows(test) {
    if (test.length > 0) {
        var r = test.split(/[ ,]+/).map(function (e) { return new RegExp(e, 'i') });
        $('tr.data').map( function (i, el) {
            (! r.map(function (j) { return j.test($(el).html())}).reduce(function (c, p) { return c && p;} )) ? $(el).hide() : $(el).show();
        });
    } else
    {
        $('tr.data').show();
    }
}
</script>
<div style="margin-bottom: 0.5em">

    {% block pagename %}
    {% endblock %}
    <div align="left" style="display:inline-block; width: 40%; margin-left: 2em"> Filter: <input type="search" id="filterstring" style="width: 80%" onkeyup="filterTableRows($('#filterstring').val())" autocomplete="off">
    </div>
    {% if hideshowcols %}
    <div align="right" style="display: inline-block; width: 40%">Show/Hide columns:
    {% for i in hideshowcols %}
        <span>{{i.name}} <input type="checkbox" id="ct{{i.name}}" onchange="showhideTableColumn({{i.order}}, $('#ct{{i.name}}').is(':checked'))" checked autocomplete="off"></span> |
    {% endfor %}
    </div>
    {% endif %}
</div>

   <div style="display: block; float:right; margin-left: auto; margin-right:5em"><span class="pagination" style="vertical-align: top; margin-right: 3em">Showing {{objects.start_index}} to {{objects.end_index}} out of {{objects.paginator.count}} entries.&nbsp;</span>
   <ul class="pagination" style="display: block-inline">
{%if objects.has_previous %}
  <li><a href="?page={{objects.previous_page_number}}">&laquo;</a></li>
{%else%}
  <li class="disabled"><a href="#">&laquo;</a></li>
{%endif%}
{% for i in objects.page_range %}
  <li{%if i == objects.number %} class="active" {%endif%}><a href="?page={{i}}">{{i}}</a></li>
{% endfor %}
{%if objects.has_next%}
  <li><a href="?page={{objects.next_page_number}}">&raquo;</a></li>
{%else%}
  <li class="disabled"><a href="#">&raquo;</a></li>
{%endif%}
  </ul>
</div>

    <table class="table table-striped table-condensed" style="width:95%">
{% block pagetable %}
{% endblock %}
    </table>
</div>

{% endblock %}

BSP/meta/poky/bitbake/lib/toaster/bldviewer/templates/simple_bfile.html
{% extends "simple_basebuildpage.html" %}

{% block pagetitle %}Files for package {{objects.0.bpackage.name}} {% endblock %}
{% block pagetable %}
    {% if not objects %}
        <p>No files were recorded for this package!</p>
    {% else %}

            <tr>
            <th>Name</th>
            <th>Size (Bytes)</th>
            </tr>

            {% for file in objects %}

            <tr class="data">
            <td>{{file.path}}</td>
            <td>{{file.size}}</td>

            {% endfor %}

    {% endif %}

{% endblock %}

BSP/meta/poky/bitbake/lib/toaster/bldviewer/templates/simple_bpackage.html
{% extends "simple_basebuildpage.html" %}

{% block pagetitle %}Packages{% endblock %}
{% block pagetable %}
    {% if not objects %}
        <p>No packages were recorded for this target!</p>
    {% else %}

            <tr>
            <th>Name</th>
            <th>Version</th>
            <th>Recipe</th>
            <th>Summary</th>
            <th>Section</th>
            <th>Description</th>
            <th>Size on host disk (Bytes)</th>
            <th>License</th>
            <th>Dependencies List (all)</th>
            </tr>

            {% for package in objects %}

            <tr class="data">
                <td><a name="#{{package.name}}" href="{% url "simple-bfile" build.pk package.pk %}">{{package.name}} ({{package.filelist_bpackage.count}} files)</a></td>
                <td>{{package.version}}-{{package.revision}}</td>
                <td>{%if package.recipe%}<a href="{% url "simple-layer_versions_recipes" package.recipe.layer_version_id %}#{{package.recipe.name}}">{{package.recipe.name}}</a>{{package.package_name}}</a>{%endif%}</td>

            <td>{{package.summary}}</td>
            <td>{{package.section}}</td>
            <td>{{package.description}}</td>
            <td>{{package.size}}</td>
            <td>{{package.license}}</td>
            <td>
        <div style="height: 3em; overflow:auto">
            {% for bpd in package.package_dependencies_source.all %}
                {{bpd.dep_type}}: {{bpd.depends_on.name}} <br/>
            {% endfor %}
        </div>
            </td>
            {% endfor %}

    {% endif %}

{% endblock %}

BSP/meta/poky/bitbake/lib/toaster/bldviewer/templates/simple_build.html
{% extends "simple_basetable.html" %}

{% block pagename %}
    <h1>Toaster - Builds</h1>
{% endblock %}

{% block pagetable %}

    {% load simple_projecttags %}
        <tr>
            <th>Outcome</th>
            <th>Started On</th>
            <th>Completed On</th>
            <th>Target</th>
            <th>Machine</th>
            <th>Time</th>
            <th>Errors</th>
            <th>Warnings</th>
            <th>Output</th>
            <th>Log</th>
            <th>Bitbake Version</th>
            <th>Build Name</th>
        </tr>
        {% for build in objects %}
        <tr class="data">
            <td><a href="{% url "simple-configuration" build.id %}">{{build.get_outcome_display}}</a></td>
            <td>{{build.started_on}}</td>
            <td>{{build.completed_on}}</td>
            <td>{% for t in build.target_set.all %}{%if t.is_image %}<a href="{% url "simple-tpackage" build.id t.id %}">{% endif %}{{t.target}}{% if t.is_image %}</a>{% endif %}<br/>{% endfor %}</td>
            <td>{{build.machine}}</td>
            <td>{% time_difference build.started_on build.completed_on %}</td>
            <td>{{build.errors_no}}:{% if  build.errors_no %}{% for error in logs %}{% if error.build == build %}{% if error.level == 2 %}<p>{{error.message}}</p>{% endif %}{% endif %}{% endfor %}{% else %}None{% endif %}</td>
            <td>{{build.warnings_no}}:{% if  build.warnings_no %}{% for warning in logs %}{% if warning.build == build %}{% if warning.level == 1 %}<p>{{warning.message}}</p>{% endif %}{% endif %}{% endfor %}{% else %}None{% endif %}</td>
            <td>TBD: determine image file list</td>
            <td>{{build.cooker_log_path}}</td>
            <td>{{build.bitbake_version}}</td>
            <td>{{build.build_name}}</td>
        </tr>

        {% endfor %}
{% endblock %}

BSP/meta/poky/bitbake/lib/toaster/bldviewer/templates/simple_configuration.html
{% extends "simple_basebuildpage.html" %}

{% block pagetitle %}Configuration{% endblock %}
{% block pagetable %}

            <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Definition history</th>
            <th>Value</th>
            </tr>

            {% for variable in objects %}

            <tr class="data">
                <td>{{variable.variable_name}}</td>
                <td>{% if variable.description %}{{variable.description}}{% endif %}</td>
                <td>{% for vh in variable.variablehistory_set.all %}{{vh.operation}} in {{vh.file_name}}:{{vh.line_number}}<br/>{%endfor%}</td>
                <td>{{variable.variable_value}}</td>
            {% endfor %}

{% endblock %}

BSP/meta/poky/bitbake/lib/toaster/bldviewer/templates/simple_layer.html
{% extends "simple_basetable.html" %}

{% block pagename %}
    <h1>Toaster - Layers</h1>
{% endblock %}

{% block pagetable %}
    {% load simple_projecttags %}

        <tr>
            <th>Name</th>
            <th>Local Path</th>
            <th>Layer Index URL</th>
            <th>Known Versions</th>
        </tr>

        {% for layer in objects %}

        <tr class="data">
            <td>{{layer.name}}</td>
            <td>{{layer.local_path}}</td>
            <td><a href='{{layer.layer_index_url}}'>{{layer.layer_index_url}}</a></td>
            <td><table>
            {% for lv in layer.versions %}
                <tr><td>
        <a href="{% url "simple-layer_versions_recipes" lv.id %}">({{lv.priority}}){{lv.branch}}:{{lv.commit}} ({{lv.count}} recipes)</a>
                </td></tr>
            {% endfor %}
            </table></td>
        </tr>

        {% endfor %}

{% endblock %}

BSP/meta/poky/bitbake/lib/toaster/bldviewer/templates/simple_task.html
{% extends "simple_basebuildpage.html" %}

{% block pagetitle %}Tasks{% endblock %}
{% block pagetable %}
    {% if not objects %}
        <p>No tasks were executed in this build!</p>
    {% else %}

            <tr>
            <th>Order</th>
            <th>Task</th>
            <th>Recipe Version</th>
            <th>Task Type</th>
            <th>Checksum</th>
            <th>Outcome</th>
            <th>Message</th>
            <th>Time</th>
            <th>CPU usage</th>
            <th>Disk I/O</th>
            <th>Script type</th>
            <th>Filesystem</th>
            <th>Depends</th>
            </tr>

            {% for task in objects %}

            <tr class="data">
                <td>{{task.order}}</td>
                <td><a name="{{task.recipe.name}}.{{task.task_name}}">
                <a href="{% url "simple-layer_versions_recipes" task.recipe.layer_version_id %}#{{task.recipe.name}}">{{task.recipe.name}}</a>.{{task.task_name}}</a></td>
                <td>{{task.recipe.version}}</td>

                {% if task.task_executed %}
                <td>Executed</td>
                {% else %}
                <td>Not Executed</td>
                {% endif %}

                <td>{{task.sstate_checksum}}</td>
                <td>{{task.get_outcome_display}}{% if task.provider %}</br>(by <a href="#{{task.provider.recipe.name}}.{{task.provider.task_name}}">{{task.provider.recipe.name}}.{{task.provider.task_name}}</a>){% endif %}
			{% if task.outcome == task.OUTCOME_CACHED %}{% for t in task.get_related_setscene %}
			<br/>({{t.task_name}} {{t.get_outcome_display}})
			{% endfor %}{%endif%}
		</td>
                <td><p>{{task.message}}</td>
                <td>{{task.elapsed_time}}</td>
                <td>{{task.cpu_usage}}</td>
                <td>{{task.disk_io}}</td>
                <td>{{task.get_script_type_display}}</td>
                <td> <table>
<tr><td>                Recipe</td><td><a target="_fileview" href="file:///{{task.recipe.file_path}}">{{task.recipe.file_path}}</a></td></tr>
<tr><td>                Source</td><td><a target="_fileview" href="file:///{{task.file_name}}">{{task.file_name}}:{{task.line_number}}</a></td></tr>
<tr><td>                Workdir</td><td><a target="_fileview" href="file:///{{task.work_directory}}">{{task.work_directory}}</a></td></tr>
<tr><td>                Log</td><td><a target="_fileview" href="file:///{{task.logfile}}">{{task.logfile}}</a><br/></td></tr>
</table>
                </td>
                <td>
            <div style="height: 3em; overflow:auto">
                {% for tt in task.task_dependencies_task.all %}
                    <a href="#{{tt.depends_on.recipe.name}}.{{tt.depends_on.task_name}}">
                    {{tt.depends_on.recipe.name}}.{{tt.depends_on.task_name}}</a><br/>
                {% endfor %}
            </div>
                </td>
                </tr>

            {% endfor %}

    {% endif %}

{% endblock %}